import "./globals.css";
import AuthRoutes from "@/components/AuthRoutes";

export const metadata = {
  title: "Thread Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={` w-full h-screen lg:overflow-hidden`}>
        <AuthRoutes>{children}</AuthRoutes>
      </body>
    </html>
  );
}
